CREATE TABLE IF NOT EXISTS Municipios_Brasileiros (
Cidade NVARCHAR(50) NOT NULL,
Estado NVARCHAR(2) NOT NULL,
Regiao NVARCHAR(20) NOT NULL,
municipio_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

DROP TABLE Municipios_Brasileiros;

CREATE TABLE Municipios_Brasileiros (
Cidade NVARCHAR(50) NOT NULL,
Estado NVARCHAR(2) NOT NULL,
Regiao NVARCHAR(20) NOT NULL,
municipio_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);